### ISSUE TITLE
Class structure is inverted and very difficult to use

### ISSUE THREAD

**Issue by jcjones** [SER516/ProjectOne#10]
For this to be useful, your top level class should be the actual object. Having the top class be a test driver is an anti-pattern. If you need a test driver, you should look into using JUnit, or simply make a second class file with your `main` method.

https://github.com/SER516/ProjectOne/blob/1e7ea4e79f9229f056cfeeb3a4890b96fc7bd78e/P107_Srivastava_Tab.java#L50

**Comment by varun1309** [comment]
closed
